<a href="https://colab.research.google.com/github/krvi28/pytorch-deeplearning/blob/main/math/01_vectors_matrix_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

#### Using Numpy

In [15]:
# create a vector
nv = np.array([ [1, 2, 3, 4] ])
print(nv), print(' ')

# transpose a vector using numpy
print(np.transpose(nv))

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]


In [16]:
# transpose a vector
print(nv.T), print(' ')

nvT = nv.T

# Transpoe a transpose
print(nvT.T)


[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [19]:
# repeat for a matrix
nM = np.array([ [1, 2, 3, 4], [5, 6, 7, 8]])

print(nM), print(' ')

# transpose the matrix
print(nM.T), print(' ')

# transpose the transpose
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


#### Using Torch

In [23]:
# transpose a matrix
tM = torch.tensor([ [1, 2, 3, 4],
                    [5, 6, 7, 8]])

print(tM), print(' ')

tMT = tM.T
print(tMT), print(' ')

# transpose a transpose
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [24]:
## examine the data types
print(f"Variable nv is of the data type: {type(nv)}")
print(f"Variable nM is of the data type: {type(nM)}")
print(f"Variable tM is of the data type: {type(tM)}")


Variable nv is of the data type: <class 'numpy.ndarray'>
Variable nM is of the data type: <class 'numpy.ndarray'>
Variable tM is of the data type: <class 'torch.Tensor'>
