<a href="https://colab.research.google.com/github/krvi28/pytorch-deeplearning/blob/main/math/03_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

#### Using Numpy

In [6]:
# Create random matrices
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

#print(np.round(A@B, 2)) # np.matmul(A, B)
#print(np.round(A@C, 2))
#print(np.round(B@C, 2))
print(np.round(C.T@A, 2))

[[-0.82 -0.04  0.59  0.44]
 [-4.65  0.38  1.91  5.44]
 [-2.82  0.45 -2.52 -0.62]
 [-3.75  0.48 -0.39  2.84]
 [-2.92  0.33 -1.13  0.52]
 [-1.47 -0.07  1.69  1.83]
 [-6.62  0.63 -0.97  2.75]]


#### Using PyTorch

In [11]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype=torch.float)

#print(np.round(A@B, 2)) # np.matmul(A, B)
#print(np.round(A@B, 2))
#print(np.round(A@C1, 2))
print(np.round(A@C2, 2))

tensor([[ 1.5400,  1.6100,  0.1500, -2.7900,  0.2400,  0.8200, -1.7500],
        [ 0.9300,  0.1100,  0.0800, -1.4100,  0.4000,  1.1200,  0.0600],
        [-0.2500,  0.0400, -0.0400,  0.1200, -0.0900, -0.1300, -0.2200]])
